// Generated by ReScript, PLEASE EDIT WITH CARE


function Make(Query) {
  var graphQLUrl = function (param) {
    return "https://clientapi.staging.sothelabs.com/graphql";
  };
  return {
          graphQLUrl: graphQLUrl,
          Query: Query
        };
}

export {
  Make ,
  
}
/* No side effect */
