// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Make(Query) {
  var graphQLUrl = function (param) {
    return "https://clientapi.staging.sothelabs.com/graphql";
  };
  return {
          graphQLUrl: graphQLUrl,
          Query: Query
        };
}

exports.Make = Make;
/* No side effect */
