// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as TestQuery from "./TestQuery.bs.js";

Curry._4(TestQuery.Test.Query.queryAndParse, undefined, undefined, undefined, undefined).then(function (response) {
      switch (response.TAG | 0) {
        case /* Data */0 :
            console.log(response._0.algoliaSearchKey.key);
            break;
        case /* DataWithError */1 :
        case /* Error */2 :
            break;
        
      }
      return Promise.resolve(undefined);
    });

export {
  
}
/*  Not a pure module */
