// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as TestQuery from "./TestQuery.bs.js";

function fetchTest(param) {
  return Curry._4(TestQuery.Test.Query.queryAndParse, undefined, undefined, undefined, undefined);
}

fetchTest(undefined).then(function (response) {
      console.log("response", response);
      if (typeof response === "object" && response.NAME === "Data") {
        console.log(response.VAL.algoliaSearchKey.key);
      }
      return Promise.resolve(undefined);
    });

export {
  fetchTest ,
  
}
/*  Not a pure module */
