// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var TestQuery = require("./TestQuery.bs.js");

function fetchOrder(param) {
  return Curry._4(TestQuery.Test.Query.queryAndParse, undefined, undefined, undefined, undefined);
}

exports.fetchOrder = fetchOrder;
/* TestQuery Not a pure module */
